# Generated by Django 4.2.4 on 2024-01-04 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myinvestment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvestmentPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('daily_return', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('monthly_return', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('referral_commission', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
            ],
        ),
    ]
