# Generated by Django 4.2.4 on 2024-01-05 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myinvestment', '0004_alter_purchased_screenshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchased',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
