# Generated by Django 4.2.4 on 2024-01-05 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myinvestment', '0006_alter_investmentplan_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchased',
            name='pending',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='investmentplan',
            name='amount',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
