# Generated by Django 4.2.4 on 2024-01-05 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myinvestment', '0007_purchased_pending_alter_investmentplan_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=30),
        ),
    ]
