# Generated by Django 4.2.4 on 2024-01-05 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myinvestment', '0009_alter_profile_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='withdrawl_amount',
            field=models.IntegerField(default=0),
        ),
    ]
