# Generated by Django 4.2.4 on 2024-01-06 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myinvestment', '0011_withdrawl_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchased',
            name='daily_return',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
