# Generated by Django 4.2.4 on 2024-01-06 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myinvestment', '0012_purchased_daily_return'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='withdrawl_request',
            name='bank',
        ),
    ]
