# Generated by Django 4.2.4 on 2024-01-07 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myinvestment', '0013_remove_withdrawl_request_bank'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='commission',
            field=models.IntegerField(default=0),
        ),
    ]
