# Generated by Django 4.2.4 on 2024-01-07 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myinvestment', '0014_profile_commission'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='purchased_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Purchase', to='myinvestment.purchased'),
        ),
    ]
