# Generated by Django 4.2.4 on 2024-01-07 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myinvestment', '0015_profile_purchased_plan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='purchased_plan',
        ),
        migrations.AddField(
            model_name='purchased',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myinvestment.profile'),
        ),
    ]
