# Generated by Django 4.2.4 on 2024-01-07 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myinvestment', '0016_remove_profile_purchased_plan_purchased_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdrawl_request',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myinvestment.profile'),
        ),
    ]
